### ISSUE TITLE
Motivation

### ISSUE THREAD

**Issue by behdad** [mta452/SheenFigure#13]
Hi,

I'm curious.  What's the motivation for writing this library?  Why couldn't you use HarfBuzz?

**Comment by mta452** [comment]
HarfBuzz is a great library, but I wanted to learn the OpenType technology. So I created a similar library in C with a different API and coding style.

**Comment by behdad** [comment]
I see.

If you decide to contribute to HarfBuzz, you're obviously more than welcome. :)
